### ISSUE TITLE
Uncaught Error: spawnSync /bin/sh ENOENT

### ISSUE THREAD

**Issue by Kanimster** [andrew-d-jackson/atom-clang-format#91]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.46.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.15.4
**Thrown From**: [clang-format](https://github.com/LiquidHelium/atom-clang-format) package 2.0.8

### Stack Trace

Uncaught Error: spawnSync /bin/sh ENOENT

```
At /Users/kanykeiimanalieva/.atom/packages/clang-format/lib/clang-format.js:107

Error: spawnSync /bin/sh ENOENT
    at Object.spawnSync (internal/child_process.js:982:20)
    at spawnSync (child_process.js:606:24)
    at execSync (child_process.js:653:13)
    at ELECTRON_ASAR.js:740:23
    at ClangFormat.format (/packages/clang-format/lib/clang-format.js:98:22)
    at /packages/clang-format/lib/clang-format.js:19:14)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:349538)
    at KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1256534)
    at KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1252668)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:284744)
```

### Commands

```
  4x -1:16.3.0 core:backspace (input.hidden-input)
     -1:12.8.0 editor:newline (input.hidden-input)
  6x -1:11.6.0 core:backspace (input.hidden-input)
     -0:47.5.0 core:move-right (input.hidden-input)
     -0:43.4.0 core:backspace (input.hidden-input)
  3x -0:37.7.0 clang-format:format (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-java 1.2.7 
clang-format 2.0.8 
gcc-make-run 0.2.12 
Hydrogen 2.14.1 
language-assembly 0.7.2 
platformio-ide-terminal 2.10.0 
```

**Comment by Kanimster** [comment]
local problem
